#!/usr/bin/env bash

set -e -x

USERID="$(id -u)"
GROUPID="$(id -g)"

xhost "+local:"
if [[ "$USERID" != "1000" ]] || [[ "$GROUPID" != "1000" ]]; then
  echo "Warning: defaulting to semi-insecure x (userid != containerUserId)"
  xhost "-local:"
fi

echo "launching parsec: (u${USERID}:g${GROUPID})"
docker run --rm --init \
 --env DISPLAY \
 --env PULSE_SERVER \
 -v /dev/snd:/dev/snd --privileged \
 -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v "/run/user/$USERID/pulse:/run/user/1000/pulse" \
 --device /dev/dri \
 --net=host \
 orandja/parsec:latest app_daemon=1
